import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Be a Hero',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ fontFamily: 'Roboto, Inter, sans-serif' }} >
        <div className="min-h-screen flex flex-col items-center px-4 sm:px-12 lg:px-24" >
          {children}
        </div>        
      </body>        
    </html>
  )
}
